- stat: path=~/go
  register: golang

- name: Download the Go tarball
  get_url:
    url: "{{ go_download_location }}"
    dest: ~/
    checksum: "{{ go_tarball_checksum }}"
  when: golang.stat.exists == False

- name: Install golang
  unarchive:
    src: ~/{{ go_tarball }}
    dest: ~/
    remote_src: yes
  when: golang.stat.exists == False

- stat: path=~/go/bin/hugo
  register: gohugo

- name: Download the Hugo tarball
  get_url:
    url: "{{ hugo_download_location }}"
    dest: ~/
  when: gohugo.stat.exists == False

- name: Install hugo
  unarchive:
    src: ~/{{ hugo_tarball }}
    dest: ~/go/bin
    remote_src: yes
  when: gohugo.stat.exists == False

- name: Create tmp path
  file: path=~/tmp state=directory mode=0755