sudo: false
language: ruby
rvm:
  - 1.9.3
  - 2.4.3
before_install:
  - wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.48/hugo_0.48_Linux-64bit.deb
  - sudo dpkg -i /tmp/hugo.deb
  - gem install bundler -v 1.16.2
  - cp config.toml.example config.toml
  - cp panel.yml.example panel.yml

