sudo: false
language: ruby
rvm:
  - 1.9.3
before_install:
  - wget -O /tmp/hugo.deb https://github.com/spf13/hugo/releases/download/v0.41/hugo_0.41_Linux-64bit.deb
  - sudo dpkg -i /tmp/hugo.deb
  - gem install bundler -v 1.16.2
