#!/bin/bash
#
# Equip a remote initialized repo with libs and tools.
#
# Full examples:
#   cd sys; rogequip rubyongo rubyongo.org
#   cd sys; rogequip username domain.name

# Args
NAME="$1@$2" # => rubyongo@rubyongo.org
REPO="$2"    # => rubyongo.org
DEPLOY_KEY="keys/deploy_$NAME.pub"

if [ -f "$DEPLOY_KEY" ]
then
  echo Equip remote rog for $NAME
  ansible-playbook -i rogs -l $1 env.yml # Setup the host environment
  ssh $NAME "cd $REPO && git stash && git pull && hugo"
  ansible-playbook -i rogs -l $1 restart.yml # Restart server
  touch $DEPLOY_KEY
else
  echo "$NAME is not yet initialized, please run: roginit $1 $2"
fi
