name = "rubyongo"
license = "rubyongo"
licenselink = "rubyongo"
description = "rubyongo hugo template"
homepage = "https://rubyongo.org"
tags = ["webshop", "framework", "code"]
features = ["webshop", "framework", "code"]
min_version = 0.1

[author]
    name = "kitschmaster"
    homepage = "https://github.com/mihael"
